# Generated by Django 5.2.1 on 2025-05-20 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='exchangeproposal',
            name='unique_proposal_pair',
        ),
        migrations.AddField(
            model_name='exchangeproposal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='exchangeproposal',
            name='ad_receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals_received_for_this_ad', to='ads.ad', verbose_name='Запрашиваемый товар (получателя)'),
        ),
        migrations.AlterField(
            model_name='exchangeproposal',
            name='ad_sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals_sent_with_this_ad', to='ads.ad', verbose_name='Предлагаемый товар (от инициатора)'),
        ),
        migrations.AlterField(
            model_name='exchangeproposal',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает ответа'), ('accepted', 'Принято'), ('rejected', 'Отклонено')], default='pending', max_length=10, verbose_name='Статус'),
        ),
        migrations.AddConstraint(
            model_name='exchangeproposal',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending'), ('status', 'accepted'), _connector='OR'), fields=('proposer', 'ad_sender', 'ad_receiver'), name='unique_active_proposal_for_ads_by_user'),
        ),
    ]
